### ISSUE TITLE
Events from other widgets are not triggered when clicking the drag widget

### ISSUE THREAD

**Issue by JitzedeGroote** [Itvisors/mendix-DragAndDropSupportWidget#8]
Hi,

I found a bug in MX 7.23.8 (not sure if its there in older versions, although I think so)

When using the drag/drop widget, the focus of other input fields in the screen is not removed and also their events are not called (on change / on leave ). 

For screenshots:
https://forum.mendixcloud.com/link/questions/97013

**Comment by mgroeneweg** [comment]
Hi,

I don't think this is related to the widget, but to how Mendix handles events. The drag/drop widgets handle events at the node where you link them too, so any events on nested widgets should go through as if the drag/drop is not there.

With regards,

Marcel

**Comment by JitzedeGroote** [comment]
Hi, 

Thanks for your response. Mendix says it handles its events when leaving the widget or clicking another widget. This works in my example until the moment the draggable widget is in the listview, at that moment it looks like mendix does not know that the draggable widget is a widget, hence not handling the on-change. So it seems like it is related to the widger, since in other widgets from the appstore the behaviour is as expected, but with this one not. 

Do you recommend to create a Mendix support action for this?

Regards,

**Comment by mgroeneweg** [comment]
Yes you could do that.

**Comment by JitzedeGroote** [comment]
Hi Marcel,

I've had contact with the Mendix Widget team and they responded the following:

---
Our developers have found the cause for this behavior, the jQuery UI library used by the drag/drop widget calls event.preventDefault() when handling the mouseDown event. This is why the text box is unable to lose the focus when the draggable item is clicked or dragged.
You can report back this to the widget developer so he can fix it.
Since this is not related to the Mendix platform I will set this ticket as solved. Should you require further assistance on this matter, please to this ticket and we will be happy to assist.
--
I've excluded the event.preventDefault() method in codeline 923 within he jQuery UI library, which indeed works, and until now I and the users from the application did not experience any other side effects. 

However, I know that this adjusting the library is not a preferred solution, so I was hoping if it is possible to change this in the draggable.js itself. Unfortunately my JS is not that well, so maybe you can help with this. And maybe its worth to fork this and improve the widget itself.

Can you help further

Regards

**Comment by mgroeneweg** [comment]
Hi,

If that fix works for you, great. The issue is with the jQueryUI library itself. And this is the first time I get such a report.

Also, I intend to create a new pluggable (React) version of the drag/drop widgets.

So I will not release the fix as I cannot oversee whether the fix has consequences for other use cases.

With regards,

marcel
